services:
  admin_app:
    build:
      context: .
      dockerfile: ./docker_images/app/Dockerfile
      args:
        DISTROLESS_VER: "debug-nonroot"
        FUNC_NAME: "admin"
    container_name: "interviewai-admin-app"
    volumes:
      - ./src/admin/bff:/app/src:cached
    command: "/app/py-packages/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8001:8000
    tty: true
    env_file:
      - .env
  client_app:
    build:
      context: .
      dockerfile: ./docker_images/app/Dockerfile
      args:
        DISTROLESS_VER: "debug-nonroot"
        FUNC_NAME: "client"
    container_name: "interviewai-client-app"
    volumes:
      - ./src/client/bff:/app/src:cached
    command: "/app/py-packages/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    tty: true
    env_file:
      - .env
